apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: deployment-strategies-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: deployment-strategies.$KUBE_NS.ingress.sre-ab.ru
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: deployment-strategies
            port:
              number: 8080